// Production entry: `pnpm build && pnpm start`
// Serves the built SvelteKit app and attaches the game WebSocket server,
// mirroring what the Vite plugin does in development.
import { createServer } from 'node:http';
import { WebSocketServer } from 'ws';
import { attachGameServer } from './src/lib/server/ws.ts';

// @ts-expect-error generated by `pnpm build`
const { handler } = await import('./build/handler.js');

const port = Number(process.env.PORT ?? 3000);
const server = createServer(handler);

const wss = new WebSocketServer({ noServer: true });
attachGameServer(wss);
server.on('upgrade', (req, socket, head) => {
	if (req.url?.split('?')[0] !== '/ws') return socket.destroy();
	wss.handleUpgrade(req, socket, head, (ws) => wss.emit('connection', ws, req));
});

server.listen(port, () => console.log(`Cambio running on http://localhost:${port}`));
